#include "NucliecAcidToolbox.hpp"

// Use uppercase only (for now)
int main()
{
    std::string sequence = "AUAGGUCAGACGUCAAGACAGCUUACUGGGUAUUAAUUGAGAAGUGGGAAUGGGUUUCAUAACCCACUCCGUUUCUUAACGGUUUAGCAUUUGCUCGUGAGGCGACAGCUACUAGGGAAAGUAGUAAUAUCCCCAUAAUUACUAGUACCAUGAUUUUAUGCUUGUUUUUAUAUCCGUAGACUCGUGCUACUAAGGCGUACUGCUAGAGGUGCACUGCCCGCAUAACUGGUUCAUACCCCGACUUGUGGCUCAGCCGCGACAGAGAGAAGGCUGGGGAGGACGGACAUGAUUAUUCUCCUCGGUCCCAUCCUCGCCAGUCUGACGCCUUCGUCACGAGCAAUAAUAAGUGGAGAUAAAGGACACUUGAACGCUGUGCAGGGCGAUCUCAGACAUUGAAGUUGAAAAUUCGCGACCACCUAGGCAAGUGACGCCGUAUCGUAGUCCUCCGUGACGACGGCGAGUGCGAUAGAACGAGCCAGAGCGCUAACUUGUCAGGCGACCCGGCUCCGGCAGGAUAGUUUCCCACAGUAUCAUAUGACAACGCAGCCAGACAGAGGACAUACGAGAGCUGAAGAUGCCACCGUACUAUUAUAUGCAUGCGGGUCUACGUCAUUUAUAAUGGACGGUCUACGGCUGAGCCCCCACACGGUAGGCCUGUUAGCCGUCUGAUGGGGGUGGUGAAGGUAGUGACUGUCCCUACCCCAUUUCCUUCGAGACCAGCGGUGUAGUCACCUCAGGAUCCACCACCGAGACCGAUGUGGGUAGCGAUCAGUAACCCGUUCAAGUACAUCUCGAAGCGUUCCUCGGCUCAACUAAUUUACGUGGGCGGAUUCGUUGUGGUACACUCGUCCUUGACUAACAUGGUAGCCAACUGCGUUGUCGGGCUCCGGCCGACGUUUGGCCAGAGCGGUACAAAGAUUCCCCCAUUCGGUGCCCUUCACGAUACUGUGUAUUACUUACCCCACUUGCGAAGAACCGAUAUUCGGGGGGUGGAGGGUAC";
    std::cout << NucliecAcidToolbox::Transcribe(sequence);  
}

/* 

Usage:
For sequences, go to https://molbiotools.com/randomsequencegenerator.php
Paste your sequence into one of the variables (char or string)

Code flow:
Overloading will call the transcribe char or string function
Transcribe will detect if the input is DNA or RNA
Transcribe will either call DnaToRna or RnaToDna
The conversion function will return the value, and the transcribe function will return that value once again

What could be changed?:
1.) (DONE)
2.) (DONE)
3.) I could generate my own sequences 
4.) I could have the user input the variable at runtime instead of compile time for input / output customizability
5.) Interactive WEB GUI for quicker results and a better user experience 
6.) Add toUpper function to automatically uppercase the string
7.) Improve code flow
8.) Use less resources

*/